version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:19

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Build
          command: npm run build

      - persist_to_workspace:
          root: /app/dist
          paths:
            - ./dist

workflows:
  version: 2
  build_and_copy:
    jobs:
      - build
